### PR TITLE
Split array at top level and filePath refactor

### PR DESCRIPTION
**Pull request by cynngah**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/gulp-i18n-csv/20)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[index.js, line 21 [r2]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20#-JzVmHDsT81kgpx5ZHK4)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/d8c4b3644ce40c073838896607fbbfe9482285a2/index.js#L21)):</sup>
If the`resPath` option is not specified, json files are not split correctly. `resPath` should have a default value of `'locales/__lng__/__ns__.json'`.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[index.js, line 25 [r3]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20#-JzWfvVcEj4M9yp6CHxU)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/dd2e06b681e730644a4480b88d03ee6ff4f9870c/index.js#L25)):</sup>
Breaks here `TypeError: Cannot call method 'replace' of undefined`. `savePath` looks to be undefined.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20)

**Comment by AleksueiR** [comment]
Great work Cynthia! Everything is splitting up nicely.
Only one small thing left to fix - when splitting sections, the split key is lost.

``` json
tab.json
--//--
{
    "rot": {
        "off": "Stop tab rotation",
        "on": "Start tab rotation"
    },
    "list": "Tab list",
    "pnl": {
        "end1": "End of this tab panel.",
        "end2": "Return to the tab list",
        "end3": "or continue to the rest of page."
    },
    "play": "Play"
}
```

This should be instead:

``` json
tab.json
--//--
{
    "tab": {
        "rot": {
            "off": "Stop tab rotation",
            "on": "Start tab rotation"
        },
        "list": "Tab list",
        "pnl": {
            "end1": "End of this tab panel.",
            "end2": "Return to the tab list",
            "end3": "or continue to the rest of page."
        },
        "play": "Play"
    }
}
```

Otherwise it's not possible to use a full key (`tab.rot.off`) in the code.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/20)

**Pull request merged**
