### PR TITLE
Style checks on Travis

### PR DESCRIPTION
**Pull request by AleksueiR**
Runs code style checks on Travis and adds Gitter notifications.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/gulp-i18n-csv/13)

### CODE REVIEW

**Comment by alyec** [comment]
Don't know what tool I was using that did two space tabs in the package.json file.  Thanks for the fix.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[.travis.yml, line 12 [r1]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13#-Jx0ZEvcH9RUJaOD3t_g)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/5a8d01404cd089ddabbe0ac3a99e9736a781615c/.travis.yml#L12)):</sup>
gitter isn't very noisy about the sidebar updates and it might be worth showing the status for all builds

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[.travis.yml, line 12 [r1]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13#-Jx0ZEvcH9RUJaOD3t_g)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/5a8d01404cd089ddabbe0ac3a99e9736a781615c/.travis.yml#L12)):</sup>
For all successes and failures?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[.travis.yml, line 12 [r1]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13#-Jx0ZEvcH9RUJaOD3t_g)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/5a8d01404cd089ddabbe0ac3a99e9736a781615c/.travis.yml#L12)):</sup>
Oh, sorry, it's already set to 'always' for failures.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13)

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[.travis.yml, line 12 [r1]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13#-Jx0ZEvcH9RUJaOD3t_g)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/5a8d01404cd089ddabbe0ac3a99e9736a781615c/.travis.yml#L12)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13)

**Comment by alyec** [comment]
> "always snow success notifications"

git commit --amend ?

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13)

**Comment by AleksueiR** [comment]
Squashed them into one commit.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13)

**Comment by alyec** [comment]
:heavy_check_mark: 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/13)

**Pull request merged**
