### PR TITLE
add error throw on bad csv formatting closes #7

### LINKED ISSUE #7: Throw error on poorly formatted csv
| key | string |
| --- | --- |
| tab | Tab |
| tab.list | Tab List |
| tab.play | Tab Play |

Converting this to JSON, the first row is lost:

``` json
{
    "tab": {
        "list": "Tab List",
        "play": "Tab Play"
    }
}
```

Throw error in this case.

### PR DESCRIPTION
**Pull request by cynngah**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/gulp-i18n-csv/16)

### CODE REVIEW

**Comment by alyec** [comment]
This handles the case where you try convert a non-leaf node into a leaf node, but I don't think it handles the opposite case.

```
node.child,"my string"
node,"I will throw an error"
```

```
node,"my string"
node.child,"I will cause problems"
```

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[index.js, line 50 [r1]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16#-JxV2zFzmVPvvrBVCKnq)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/5bd672c146ca71594c4dc117acc3bc093631cfd0/index.js#L50)):</sup>
I think multistr is only used if you use \ to create a multi line string.  Concats should be fine.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[index.js, line 52 [r1]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16#-JxV3AEEkU3ib_DtrEpA)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/5bd672c146ca71594c4dc117acc3bc093631cfd0/index.js#L52)):</sup>
We might want to fix the main sample file, as the plugin will fail there and create another, smaller failing sample file for future testing.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16)

**Comment by cynngah** [comment]
Added other case

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16)

**Comment by cynngah** [comment]
<sup>**[index.js, line 55 [r1]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16#-JxV3AEEkU3ib_DtrEpA)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/5bd672c146ca71594c4dc117acc3bc093631cfd0/index.js#L55)):</sup>
Sample file shouldn't fail anymore

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16)

**Comment by cynngah** [comment]
<sup>**[index.js, line 54 [r1]](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16#-JxV2zFzmVPvvrBVCKnq)** ([raw file](https://github.com/fgpv-vpgf/gulp-i18n-csv/blob/5bd672c146ca71594c4dc117acc3bc093631cfd0/index.js#L54)):</sup>
thanks for pointing that out, forgot to delete after i changed from \ to +

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/gulp-i18n-csv/16)

**Pull request merged**
